import type { CompanyJobDetail } from '@/types/company-job-detail';

// Mock database for job details.
// Replace this with real API calls later.
const JOBS_DATABASE: Record<string, CompanyJobDetail> = {
  '1': {
    id: '1',
    title: 'Office Electrical Rewiring',
    company: 'Tech Corp Ltd',
    trade: 'Electrician',
    status: 'in-progress',
    location: 'London, EC1',
    address: '123 Business Street, London, EC1A 1AA',
    startDate: '2025-11-25',
    endDate: '2025-11-27',
    workersNeeded: 2,
    description:
      'Complete rewiring of office space including installation of new circuit breakers, lighting fixtures, and power outlets. Must comply with current electrical safety standards.',
    requirements: [
      'Level 3 NVQ in Electrical Installation',
      'Current ECS Gold Card',
      '18th Edition Wiring Regulations',
    ],
    dailyRate: 280,
    allocatedWorkers: [
      {
        id: 'w1',
        name: 'James Wilson',
        phone: '+44 7700 900123',
        email: 'james.wilson@example.com',
        rating: 4.8,
        jobsCompleted: 142,
      },
      {
        id: 'w2',
        name: 'Sarah Thompson',
        phone: '+44 7700 900456',
        email: 'sarah.t@example.com',
        rating: 4.9,
        jobsCompleted: 98,
      },
    ],
    paymentId: 'pay-1',
    paymentStatus: 'stripe-hold',
    createdAt: '2025-11-20',
    startedAt: '2025-11-25T09:00:00',
    completedAt: null,
    platformFee: 56,
    labourCost: 560,
    totalCost: 616,
    timeline: [
      { date: '2025-11-20', event: 'Job created', status: 'completed' },
      { date: '2025-11-21', event: 'Workers allocated', status: 'completed' },
      { date: '2025-11-22', event: 'Workers accepted', status: 'completed' },
      { date: '2025-11-24', event: 'Platform fee paid', status: 'completed' },
      { date: '2025-11-25', event: 'Job started', status: 'completed' },
      { date: '2025-11-27', event: 'Expected completion', status: 'pending' },
    ],
  },
  '2': {
    id: '2',
    title: 'Bathroom Plumbing Installation',
    company: 'Tech Corp Ltd',
    trade: 'Plumber',
    status: 'allocated',
    location: 'Manchester, M1',
    address: '45 Water Lane, Manchester, M1 2AB',
    startDate: '2025-11-28',
    endDate: '2025-11-28',
    workersNeeded: 1,
    description:
      'Install new bathroom suite including bathtub, sink, toilet, and all necessary plumbing connections.',
    requirements: ['NVQ Level 2/3 Plumbing', 'Public Liability Insurance'],
    dailyRate: 320,
    allocatedWorkers: [
      {
        id: 'w3',
        name: 'Michael Brown',
        phone: '+44 7700 900789',
        email: 'm.brown@example.com',
        rating: 4.7,
        jobsCompleted: 76,
      },
    ],
    paymentId: 'pay-2',
    paymentStatus: 'platform-fee-paid',
    createdAt: '2025-11-22',
    startedAt: null,
    completedAt: null,
    platformFee: 32,
    labourCost: 320,
    totalCost: 352,
    timeline: [
      { date: '2025-11-22', event: 'Job created', status: 'completed' },
      { date: '2025-11-23', event: 'Workers allocated', status: 'completed' },
      { date: '2025-11-23', event: 'Workers accepted', status: 'completed' },
      { date: '2025-11-24', event: 'Platform fee paid', status: 'completed' },
      { date: '2025-11-28', event: 'Scheduled start', status: 'pending' },
    ],
  },
  '3': {
    id: '3',
    title: 'Kitchen Cabinet Installation',
    company: 'Tech Corp Ltd',
    trade: 'Carpenter',
    status: 'pending',
    location: 'Birmingham, B1',
    address: '78 Oak Street, Birmingham, B1 3CD',
    startDate: '2025-12-01',
    endDate: '2025-12-02',
    workersNeeded: 2,
    description: 'Install custom kitchen cabinets and worktops. Precision required for fitted units.',
    requirements: ['NVQ Carpentry', 'Experience with fitted kitchens'],
    dailyRate: 280,
    allocatedWorkers: [],
    paymentId: null,
    paymentStatus: 'unpaid',
    createdAt: '2025-11-23',
    startedAt: null,
    completedAt: null,
    platformFee: 56,
    labourCost: 560,
    totalCost: 616,
    timeline: [
      { date: '2025-11-23', event: 'Job created', status: 'completed' },
      { date: 'TBD', event: 'Workers allocation', status: 'pending' },
    ],
  },
  '4': {
    id: '4',
    title: 'Warehouse Painting',
    company: 'Tech Corp Ltd',
    trade: 'Painter',
    status: 'completed',
    location: 'Leeds, LS1',
    address: '22 Industrial Park, Leeds, LS1 4EF',
    startDate: '2025-11-18',
    endDate: '2025-11-20',
    workersNeeded: 3,
    description: 'Interior painting of warehouse facility. Walls and ceiling coverage required.',
    requirements: ['CSCS Card', 'Commercial painting experience'],
    dailyRate: 250,
    allocatedWorkers: [
      {
        id: 'w4',
        name: 'David Lee',
        phone: '+44 7700 900111',
        email: 'd.lee@example.com',
        rating: 4.6,
        jobsCompleted: 134,
      },
      {
        id: 'w5',
        name: 'Emma Davis',
        phone: '+44 7700 900222',
        email: 'emma.d@example.com',
        rating: 4.8,
        jobsCompleted: 89,
      },
      {
        id: 'w6',
        name: 'Tom Harris',
        phone: '+44 7700 900333',
        email: 't.harris@example.com',
        rating: 4.5,
        jobsCompleted: 67,
      },
    ],
    paymentId: 'pay-4',
    paymentStatus: 'released',
    createdAt: '2025-11-15',
    startedAt: '2025-11-18T08:00:00',
    completedAt: '2025-11-20T17:00:00',
    platformFee: 75,
    labourCost: 750,
    totalCost: 825,
    timeline: [
      { date: '2025-11-15', event: 'Job created', status: 'completed' },
      { date: '2025-11-16', event: 'Workers allocated', status: 'completed' },
      { date: '2025-11-16', event: 'Workers accepted', status: 'completed' },
      { date: '2025-11-17', event: 'Payment processed', status: 'completed' },
      { date: '2025-11-18', event: 'Job started', status: 'completed' },
      { date: '2025-11-20', event: 'Job completed', status: 'completed' },
      { date: '2025-11-21', event: 'Payment released', status: 'completed' },
    ],
  },
};

export async function getCompanyJobDetail(jobId: string): Promise<CompanyJobDetail | null> {
  // TODO: Replace with real API call.
  return Promise.resolve(JOBS_DATABASE[jobId] ?? null);
}
